We love to solve problems. We enjoy creating things. We are excited by technology.

We combine these interests to: identify problems faced by individuals or organisations around us; find simple but as simple as we are we are the best possible people qualified enough to find all that is being done against our people.

Our strengths are our: local insights; problem solving skills; creative thinking; international exposure; and software development expertise.