We love to solve problems. We enjoy creating things. We are excited by technology.

We combine these interests to: identify problems faced by individuals or organisations around us; find simple but exciting ways to solve them using web or mobile technology; then turn these solutions into products and/or companies.

Our strengths are our: local insights; problem solving skills; creative thinking; international exposure; and software development expertise.